#Currency Converter Pro - user settings
#Thu Aug 06 18:15:26 IST 2026
animations=true
autoSaveHistory=true
dailyCount=5
dailyDate=2026-08-06
defaultFrom=AED
defaultTo=EUR
fontSize=Medium
language=English
lastAmount=
soundEffects=false
theme=Light
totalCount=17
